### ISSUE TITLE
Graph.property method issues

### ISSUE THREAD

**Issue by dfcarpenter** [Revmaker/gremlex#78]
**Graph.property method does not work in the latest tinkerpop server version**

Fresh install. More or less following along with the [Medium announcement post.](https://medium.com/carlabs/introducing-gremlex-6f685adf73bd)

latest tinkerpop server version is 3.4.0
```
iex(1)> alias Gremlex.Graph
Gremlex.Graph
iex(2)> alias Gremlex.Client
Gremlex.Client
iex(3)> Graph.g() |> Graph.add_v("Language") |> Client.query
{:ok, [%Gremlex.Vertex{id: 15, label: "Language", properties: %{}}]}
iex(4)> Graph.g() |> Graph.v(15) |> Graph.property("family", "Finno-Ugaric") |> Client.query
{:ok, [%Gremlex.Vertex{id: 15, label: "Language", properties: %{}}]}
```
No matter how I try to update the properties using Gremlex, even using raw queries
```
Client.query("""
          g.addV('person').property('name','marko').next()
          """)
{:ok, [%Gremlex.Vertex{id: 0, label: "person", properties: %{}}]}
```

I then downloaded gremlin-server-3.3.5 and it works
```
iex(3)> Graph.g() |> Graph.add_v("Language") |> Client.query
{:ok, [%Gremlex.Vertex{id: 0, label: "Language", properties: %{}}]}
iex(4)> Graph.g() |> Graph.v(15) |> Graph.property("family", "Finno-Ugaric") |> Client.query
{:ok, []}
iex(5)> Graph.g() |> Graph.v(0) |> Graph.property("family", "Finno-Ugaric") |> Client.query  
{:ok,
 [
   %Gremlex.Vertex{
     id: 0,
     label: "Language",
     properties: %{family: ["Finno-Ugaric"]}
   }
 ]}

```
So it seems the newest version has changed something about how properties are handled? I skimmed the changelog but i'm new to gremlin/tinkerop and not sure what would be effecting this. If I have more time I can try to figure out what has changed. I realize you're using Neptune which i'm assuming works like tinkerpop-server-3.3.5 so this wouldn't be a high priority

**Comment by kevmojay** [comment]
Looks like there was a change involved with 3.4.0 but I will dig further to understand.

The query is adding the property but the response isn't showing it.

if you do
```
Graph.g() |> Graph.v(15) |> Graph.properties |> Client.query
```

You will see the properties on the vertex.

I will look more into exactly why the response has changed.

**Comment by kevmojay** [comment]
@dfcarpenter http://tinkerpop.apache.org/docs/3.4.0/upgrade/#_referenceelementstrategy
Here is the change that we think caused the response to be different.

I am still trying to understand where we can change it in the server configuration but overall I think, it's just the new default behavior of Gremlin. Which means i should update that medium article to prevent confusion. So thank you for bringing it up!

**Comment by dfcarpenter** [comment]
Thank you for Gremlex! Really enjoyed the Elixir Mix podcast. Also can you recommend any resources for properly modeling graph databases? Best practices, examples, etc?

**Comment by kevmojay** [comment]
One of my favorite resources for building queries is http://kelvinlawrence.net/book/Gremlin-Graph-Guide.html

As for modeling, I don't know of any good sources. Graph DBs are insanely flexible.

What has worked for us at Carlabs, is that labels on vertices describe what kind of vertex it is, labels on edges describe the relationship and then everything else is just data. 

(person) -----hasFriend---->(person)-----hasFamily--->(person)

We like this because it becomes kind of like a sentence. `Oh Kevmo has a friend Barak and Barak has family member Bruce`.
